image: ubuntu_19_04_nvm:latest

matrix:
  - env: SCRIPT=test NODE_VERSION=8
  - env: SCRIPT=test NODE_VERSION=9
  - env: SCRIPT=test NODE_VERSION=10
  - env: SCRIPT=test NODE_VERSION=11
  - env: SCRIPT=test NODE_VERSION=12

before_install:
  - nvm install $NODE_VERSION
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi

cache:
  - node_modules
